platform:ios,'8.1'

target 'BuDeJie' do
  pod 'AFNetworking'
  pod 'SDWebImage'
  pod 'FMDB'
  pod 'MBProgressHUD'
  pod 'Masonry'
  pod 'MJRefresh'
  pod 'IQKeyboardManager'
  pod 'YYModel'
  pod 'SVProgressHUD'
end
